# Generated by Django 4.2.4 on 2023-08-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0002_alter_campaign_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='percentage_of_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
