# Generated by Django 4.2.4 on 2023-08-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0003_campaign_percentage_of_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
