# Generated by Django 4.2.4 on 2023-08-23 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0004_contribution_invoice_contribution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='invoice',
        ),
    ]
