# Generated by Django 4.2.4 on 2023-08-23 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0005_remove_contribution_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
